### Cadastrar Consumo - POST
POST http://localhost:5171/AntonyWippich/consumo/cadastrar
Content-Type: application/json

{
  "cpf": "123.456.789-03",
  "mes": 10,
  "ano": 2025,
  "m3Consumidos": 10,
  "bandeira": "Amarela",
  "possuiEsgoto": true
}



### Listar Consumo - GET
GET http://localhost:5171/AntonyWippich/consumo/listar

### Buscar Consumo -GET
GET http://localhost:5171/AntonyWippich/consumo/buscar/123.456.789-03



### Remover Consumo - DELETE
DELETE http://localhost:5171/AntonyWippich/consumo/remover/123.456.789-03

### Total Geral de Faturas - GET
GET http://localhost:5171/AntonyWippich/consumo/total-geral

