// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AntonyWippich.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251020224431_AdicionandoTabelaClientes")]
    partial class AdicionandoTabelaClientes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("AntonyWippich.Models.Cliente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("adicionalBandeira")
                        .HasColumnType("REAL");

                    b.Property<int>("ano")
                        .HasColumnType("INTEGER");

                    b.Property<string>("bandeira")
                        .HasColumnType("TEXT");

                    b.Property<double>("consumoFaturado")
                        .HasColumnType("REAL");

                    b.Property<string>("cpf")
                        .HasColumnType("TEXT");

                    b.Property<double>("m3Consumidos")
                        .HasColumnType("REAL");

                    b.Property<int>("mes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("possuiEsgoto")
                        .HasColumnType("INTEGER");

                    b.Property<double>("tarifa")
                        .HasColumnType("REAL");

                    b.Property<double>("taxaEsgoto")
                        .HasColumnType("REAL");

                    b.Property<double>("total")
                        .HasColumnType("REAL");

                    b.Property<double>("valorAgua")
                        .HasColumnType("REAL");

                    b.HasKey("id");

                    b.ToTable("Clientes");
                });
#pragma warning restore 612, 618
        }
    }
}
